### ISSUE TITLE
Sealed Script - Impacts CP4D Instance

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-util-sealed-secret-cert#5]
Here is the error message which happens during the CP4D build instance stage test

│ Error: local-exec provisioner error
│ 
│   with module.gitops_ibm_catalogs.module.pull_secret.module.seal_secrets.null_resource.seal_secrets,
│   on .terraform/modules/gitops_ibm_catalogs.pull_secret.seal_secrets/main.tf line 14, in resource "null_resource" "seal_secrets":
│   14:   provisioner "local-exec" {
│ 
│ Error running command
│ '.terraform/modules/gitops_ibm_catalogs.pull_secret.seal_secrets/scripts/seal-secrets.sh
│ '/tmp/workspace/.tmp/ibm-entitlement-key/secrets'
│ '/tmp/workspace/.tmp/ibm-entitlement-key/sealed-secrets'': exit status 2.
│ Output: Kubeseal cert
│ -----BEGIN CERTIFICATE-----
│ MIIFkTCCA3mgAwIBAgIRAJRavpzJk+7/xknqRVNKPXUwDQYJKoZIhvcNAQELBQAw
│ MDEWMBQGA1UEChMNc2VhbGVkLXNlY3JldDEWMBQGA1UEAxMNc2VhbGVkLXNlY3Jl
│ dDAeFw0yMjA1MDYwOTI1MjFaFw0yMzA1MDYwOTI1MjFaMDAxFjAUBgNVBAoTDXNl
│ YWxlZC1zZWNyZXQxFjAUBgNVBAMTDXNlYWxlZC1zZWNyZXQwggIiMA0GCSqGSIb3
│ DQEBAQUAA4ICDwAwggIKAoICAQDbL15P6lQ8IyAEZNbAwFvDshL02sNHFlusDppr
│ UEg3mDma4ul1KxVg7M1ZFV5La9wJnAOoE7yCYwf58Jxc3q6TJLK0sgxqnSt60vN6
│ J2uJPf+rO7LMa+FzKOWal2Mgnd9gSdu1V5QipNwaxHo2afBKv/U1O+6AhzwJdtX1
│ TpvBv98wSTjyp1MdEuqVnIIyqbitH3u9eoIm33GvZi/+pP58ND3SpNLpqCMHlfy4
│ 0rIdePnBvkbuQ1kuZyJwTgUyumKjgCZT1qFPajIzdy+8+IhBq9IWGmK/XllLA4/+
│ hTXE52eBANBGRsjZRmgVcWQ7zspseiMek2NZ1Fkqy0DvUoIYGEVMvfVPATnSqDwC
│ MSAwu1oOPwcdieqYKNxTa4sjFDR2dU2a7+OSi08VLKzSSZWP5zgLaSpT5oAx4ERk
│ riVqpiHyWo7sFurtjozsN16XPB+8NuD6Oe2H22jcYQ2YtXmrgObndfO3gPZpNCsa
│ WOZXqRkAy38xzdJOiXMpmSXc1xc1ZQbQYcwgKTDYQ+aGbsQFaC0x5tLg/+M1Z9aJ
│ 15vtWNZxmMljnlDlwFuq0f4rOVCgnZ03RaKBBeqFMidu9uRhnxXuQf2jljTUz2Xy
│ PaxaRIBNqT6JYYYeih4mnHYd1HZXB1hMCb+5G/6Hz8wFy0U2jMeS1Wn6LFAsPYAf
│ p6SwlQIDAQABo4GlMIGiMA8GA1UdDwEB/wQFAwMH/4AwgYAGA1UdJQR5MHcGBFUd
│ JQAGCCsGAQUFBwMBBggrBgEFBQcDAgYIKwYBBQUHAwMGCCsGAQUFBwMEBggrBgEF
│ BQcDBQYIKwYBBQUHAwYGCCsGAQUFBwMHBggrBgEFBQcDCAYIKwYBBQUHAwkGCisG
│ AQQBgjcKAwMGCWCGSAGG+EIEATAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUA
│ A4ICAQCAq2ccuM1gzBgbEGEzSGe2eLE0qgeNfxkOKbv/xMMbzm9W8RlAbO7Rmuon
│ uUKAji3PuHQuH4kVC+N/RYZg3HX9MT2LtiTOq0B8vQmWROqZTapfrlpsqQwXl9YP
│ caTSGEIbgr1Uk5h/yvKsrL1p+DCOkjGudYztDWLDGooXnR2DUGi2gdDkf22atrkc
│ mnNPMVk+ufFbNPCoX2EoYcu/bZYjf9AwIhRkYFHHZqOMg55hJeVKRpFLoIa/swE8
│ VEx4uszxoywtXaUQJZvZpM45Fc8WHvlvEzrCmHQu+Zwz0Q3AJANwJRGQbukA4R7o
│ vD97XmHnB0ypdgy8ZsZAEPfKDRh+60GoR5HkDBbO9zjpVEklZgV2PZX5M6sQzAiH
│ X5Ocs+OcvOzwbFYI4P8Qm1Na1LkCMHy2/2rWj03UJsA9VzILgg0zDyNPFjbNc8aD
│ 8/34AKgiecsvZ0c0lpQesQev3ntfWhLJANXy+mabpQi6qj/0ATFVKY1pl/Vfl9WO
│ cv5znOTfygjXIXJKTUmOm/+mu0pP1uPd2wOVQ8H36Aa+KRm9QM5lIZhEeN2nEEcf
│ EEHOdCgheCSMKo9oU91YWvC5HujOXDh4xbj5YsO4pOPk81xPdZ3TYMkMFRlmHAWC
│ BKtOPS+dAFFggsmIfFFiInyJePXCae5NuN5LutKLZLuWGrapcQ==
│ -----END CERTIFICATE-----
│ 
│ 
│ panic: attempted to parse unknown event: none [recovered]
│ 	panic: attempted to parse unknown event: none
│ 
│ goroutine 1 [running]:
│ gopkg.in/yaml%2ev2.handleErr(0xc00017d980)
│ 	/home/runner/go/pkg/mod/gopkg.in/yaml.v2@v2.4.0/yaml.go:249 +0x6d
│ panic({0x1296880, 0xc000402480})
│ 	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/panic.go:1038 +0x215
│ gopkg.in/yaml%2ev2.(*parser).parse(0xc000320900)
│ 	/home/runner/go/pkg/mod/gopkg.in/yaml.v2@v2.4.0/decode.go:158 +0x154
│ gopkg.in/yaml%2ev2.(*Decoder).Decode(0xc00017d9f0, {0x1259540, 0x20c98e8})
│ 	/home/runner/go/pkg/mod/gopkg.in/yaml.v2@v2.4.0/yaml.go:122 +0x107
│ github.com/bitnami-labs/sealed-secrets/pkg/multidocyaml.isMultiDocumentYAML({0xc0001b7800,
│ 0x344, 0x400})
│ 	/home/runner/work/sealed-secrets/sealed-secrets/pkg/multidocyaml/multidocyaml.go:14
│ +0x205
│ github.com/bitnami-labs/sealed-secrets/pkg/multidocyaml.EnsureNotMultiDoc({0xc0001b7800,
│ 0xc000124000, 0x20c95c0})
│ 	/home/runner/work/sealed-secrets/sealed-secrets/pkg/multidocyaml/multidocyaml.go:19
│ +0x1e
│ main.readSecret({0x7f41ad3f9e58, 0xc000408640}, {0x1621e60, 0xc000124000})
│ 	/home/runner/work/sealed-secrets/sealed-secrets/cmd/kubeseal/main.go:141
│ +0x5d
│ main.seal({0x1621e60, 0xc000124000}, {0x1621e80, 0xc000124008},
│ {0xc0001e81c0, {0x1621780, 0xc00011a8d0}, {0xc0001cac40, 0x3, 0x4}, ...},
│ ...)
│ 	/home/runner/work/sealed-secrets/sealed-secrets/cmd/kubeseal/main.go:256
│ +0x109
│ main.run({0x16445f0, 0xc000122000}, {0x1621e80, 0xc000124008}, {0x0,
│ 0x7f41d40bba11}, {0x0, 0x0}, {0x0, 0x0}, ...)
│ 	/home/runner/work/sealed-secrets/sealed-secrets/cmd/kubeseal/main.go:741
│ +0xc79
│ main.main()
│ 	/home/runner/work/sealed-secrets/sealed-secrets/cmd/kubeseal/main.go:748
│ +0x33c
│

**Comment by balasgit** [comment]
Cluster was rebuilt and more details can be found here - https://ibm-cloudplatform.slack.com/archives/C02KB99P2JC/p1652147879272229
